config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  get '/upload' => "welcome#upload"

  resources :users, only: [:index] do
    collection  do
      post :import
    end
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord

  validates_presence_of :name, :birthday, :number, :description

  def self.import(file)
    if File.extname(file.original_filename) != ".csv"
      return false
    else
      CSV.foreach(file.path, headers: true) do |row|
        name, birthday, number, description = row.to_hash['name'], row.to_hash['date'],row.to_hash['number'],row.to_hash['description']
        User.find_or_create_by(name:name, birthday:birthday,number:number,description:description)
      end
      return true
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/users_controller.rb
class UsersController < InheritedResources::Base

  def import
    if User.import(params[:file])
      flash[:notice] = "Import successfully."
      redirect_to users_path, notice: "Users has been successfully imported."
    else
      flash[:error] = "Something went wrong. Please check the file format."
      render 'welcome/upload'
    end
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index; end

  def upload; end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.slim
doctype html
html

  head
    title Test
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags
    -#= favicon_link_tag 'favicon.png'
    meta[name="viewport" content="width=device-width, initial-scale=1.0"]
    meta[charset="UTF-8"]

  body
    header= render "shared/header"
    .container#main
      = render "shared/flash_message"
      = yield

    footer= render "shared/footer"

app/views/shared/_flash_message.slim
.flash_notice

  - if flash[:error]
    .alert.alert-danger.alert-dismissable.fade.in
      a.close[href="#" data-dismiss="alert" aria-label="close"]
        | ×
      = flash[:error]

  - elsif flash[:notice]
    .alert.alert-success.alert-dismissable.fade.in
      a.close[href="#" data-dismiss="alert" aria-label="close"]
        | ×
      = flash[:notice]

app/views/shared/_footer.slim
/ | Copyright © 2018 Uploader
/ ul.f-menu
/   li
/     a[href="/"]
/       | Home
/   li
/     a[href="/upload"]
/       | Uplaod
/   li
/     a[href="/users"]
/       | Users
/   li
/     a[href=""]
/       | Support
/   li
/     a[href=""]
/       | Contact

app/views/shared/_header.slim
nav.navbar.navbar-inverse
  .container-fluid
    .navbar-header
      a.navbar-brand[href="/"]
        | Uploader
    ul.nav.navbar-nav.navbar-right
      li
        a[href="/upload"]
          span.glyphicon.glyphicon-upload
          |  Upload
      li
        a[href="/users"]
          span.glyphicon.glyphicon-list
          |  Users

app/views/users/index.slim
table.data-table
  thead
    tr
      th #
      th Name
      th Birthday
      th Number
      th Description
  tbody
    - @users.each_with_index do |user, index|
      tr
        td= user.id
        td= user.name
        td= user.birthday.strftime("%Y-%m-%d")
        td= user.number
        td= user.description

app/views/welcome/index.html.slim
h1 Visit.org Sample Project
p
  | Please complete the items on the checklist.
  
  span<> = link_to 'This is the CSV to use.', 'test.csv'

h3 Checklist
ol
  li Create model to store CSV data
  li Upload CSV via a form
  li Save CSV records to database
  li Display success/error message
  li Display users in table

app/views/welcome/upload.slim
.row
  .col-md-9
    h4.text-muted Upload Users

.row
  .col-md-9
    = form_tag import_users_path, multipart: true do
      .col-md-4= file_field_tag :file, required: true
      .col-md-4= submit_tag "Import"